// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import type { Metadata } from "next";
import { Button } from "@/components/ui/button";
import { FaWhatsapp } from "react-icons/fa";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
  title: "AgriSense",
  description: "Agriculture platform",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Navbar */}
        <nav className="flex justify-between items-center px-8 py-5 bg-white/80 backdrop-blur shadow-sm sticky top-0 z-50">
          <div className="flex items-center gap-2">
            <Image
              src="/logo_final.png" 
              alt="AgriSense"
              width={40}
              height={40}
              className="rounded-full"
            />
            <span className="font-bold text-xl tracking-tight text-green-700">
              AgriSense
            </span>
          </div>

          <div className="hidden md:flex gap-8 text-lg font-medium text-gray-700">
            <Button asChild variant="ghost" className="text-lg">
              <Link href="/">Home</Link>
            </Button>
            <Button asChild variant="ghost" className="text-lg">
              <Link href="/about">About Us</Link>
            </Button>
            <Button asChild variant="ghost" className="text-lg">
              <Link href="/chat">Chat</Link>
            </Button>
            {/* <Button asChild variant="ghost" className="text-lg">
              <Link href="/services">Services</Link>
            </Button> */}
          </div>

          <Button className="bg-green-600 hover:bg-green-700 text-white rounded-full px-5 text-lg">
            <Link href="/login">Sign In</Link>
          </Button>
        </nav>

        {/* Page Content */}
        {children}
        {/* Floating WhatsApp Button */}
        <a
          href="https://wa.me/911234567890" // 👈 replace with your WhatsApp number
          target="_blank"
          rel="noopener noreferrer"
          className="fixed bottom-6 right-6 bg-green-500 hover:bg-green-600 text-white p-4 rounded-full shadow-lg flex items-center justify-center"
        >
          <FaWhatsapp size={50} />
        </a>
      </body>
    </html>
  );
}
